linters-settings:
  govet:
    enable:
      - shadow
  revive:
    min-confidence: 0
    rules:
      # Disabled: Would require breaking API changes (Ids -> IDs)
      - name: var-naming
        disabled: true
      # Disabled: Parameters often required for interface compliance
      - name: unused-parameter
        disabled: true
      # Disabled: Style preference, not a bug
      - name: superfluous-else
        disabled: true
      # Disabled: Would require breaking API changes (stuttering names)
      - name: exported
        disabled: true
  gocyclo:
    min-complexity: 16
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy
  gofmt:
    simplify: false

linters:
  disable-all: true
  enable:
    # Core linters
    - govet
    - typecheck
    - ineffassign
    - gofmt

    # Static analysis
    - staticcheck
    - gosimple
    - unused

    # Security
    - gosec

    # Style and quality
    - revive
    - stylecheck

    # Code complexity
    - gocyclo
    - dupl
    - gocritic
    - nakedret

    # Performance
    - prealloc
    - unconvert

    # Correctness
    - unparam
    - misspell

    # Loop variable capture (Go 1.22+)
    - copyloopvar
  fast: false

  # Enable additional checks
  enable-all: false

run:
  concurrency: 4

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec
  exclude-use-default: false

service:
  golangci-lint-version: 1.64.x
