linters-settings:
 govet:
   enable:
     - shadow
 # golint removed in newer versions, but works in v1.54.2
 golint:
   min-confidence: 0
 gocyclo:
   min-complexity: 16
 # maligned removed - replaced by govet fieldalignment
 dupl:
   threshold: 100
 goconst:
   min-len: 2
   min-occurrences: 2
 misspell:
   locale: US
 lll:
   line-length: 140
 gocritic:
   enabled-tags:
     - performance
     - style
     - experimental
   disabled-checks:
     - wrapperFunc
     - hugeParam
     - rangeValCopy
 gofmt:
   simplify: false

linters:
 disable-all: true
 enable:
   # Core linters
   - govet
   - typecheck
   - ineffassign
   - gofmt
   
   # Static analysis
   - staticcheck
   - gosimple
   - unused
   
   # Security
   - gosec
   
   # Style and quality
   - golint  # deprecated but still works in v1.54.2
   - stylecheck
   
   # Code complexity
   - gocyclo
   - dupl
   - gocritic
   - nakedret
   
   # Performance
   - prealloc
   - unconvert
   
   # Correctness
   - unparam
   - misspell
   
   # Replacing deprecated linters
   - exportloopref  # replaces scopelint (works in v1.54.2)
   # - fieldalignment # replaces maligned (in govet)
 fast: false
 
 # Enable additional checks
 enable-all: false

run:
 concurrency: 4

issues:
 exclude-dirs:
   - vendor
 exclude-rules:
   - text: "weak cryptographic primitive"
     linters:
       - gosec
 exclude-use-default: false

service:
 golangci-lint-version: 1.54.x
