name: Source clear

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Runs "weekly"
    - cron: '0 0 * * 0'

jobs:
  source_clear:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.0'
          check-latest: true
      - name: Source clear scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: |
          go mod tidy
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s - scan
